[2021-06-27 20:32:16,184] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: mysqltomongo.export_mysql_invoice 2021-06-27T20:31:36.477408+00:00 [queued]>
[2021-06-27 20:32:16,215] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: mysqltomongo.export_mysql_invoice 2021-06-27T20:31:36.477408+00:00 [queued]>
[2021-06-27 20:32:16,216] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 20:32:16,217] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-27 20:32:16,227] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 20:32:16,251] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): export_mysql_invoice> on 2021-06-27T20:31:36.477408+00:00
[2021-06-27 20:32:16,272] {standard_task_runner.py:52} INFO - Started process 3178 to run task
[2021-06-27 20:32:16,281] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mysqltomongo', 'export_mysql_invoice', '2021-06-27T20:31:36.477408+00:00', '--job-id', '128', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mysqlmongo.py', '--cfg-path', '/tmp/tmpq5bi3tt3', '--error-file', '/tmp/tmpzsupf2vj']
[2021-06-27 20:32:16,286] {standard_task_runner.py:77} INFO - Job 128: Subtask export_mysql_invoice
[2021-06-27 20:32:16,354] {logging_mixin.py:104} INFO - Running <TaskInstance: mysqltomongo.export_mysql_invoice 2021-06-27T20:31:36.477408+00:00 [running]> on host b69deda3a989
[2021-06-27 20:32:16,445] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=tech@innospark.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mysqltomongo
AIRFLOW_CTX_TASK_ID=export_mysql_invoice
AIRFLOW_CTX_EXECUTION_DATE=2021-06-27T20:31:36.477408+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-27T20:31:36.477408+00:00
[2021-06-27 20:32:16,447] {logging_mixin.py:104} INFO - Entering export_mysql_to_csv docker-mysql
[2021-06-27 20:32:16,470] {base.py:78} INFO - Using connection to: id: docker-mysql. Host: 172.27.240.1, Port: 3306, Schema: , Login: root, Password: ***, extra: {'charset': 'utf8', 'local_infile': True}
[2021-06-27 20:32:16,516] {python.py:151} INFO - Done. Returned value was: None
[2021-06-27 20:32:16,532] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=mysqltomongo, task_id=export_mysql_invoice, execution_date=20210627T203136, start_date=20210627T203216, end_date=20210627T203216
[2021-06-27 20:32:16,572] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-06-27 20:32:16,622] {local_task_job.py:151} INFO - Task exited with return code 0
